server:
  port: 8080

keycloak:
  client-id: server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: [ "${keycloak.client-id}", client ]
          issuer-uri: "http://localhost:8000/auth/realms/realm"
